sudo: true

language: php
php:
  - 5.5
  - 5.6

install:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer install

services:
    - mongodb
    - redis-server

after_script:
  - |
    if [ $TRAVIS_PHP_VERSION = '5.6' ]; then
      travis_retry wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover coverage.clover
    fi

before_script:
  - pecl install pthreads

cache:
  directories:
    - vendor
    - $HOME/.composer/cache
